### ISSUE TITLE
ext_localconf lines 22 and following destroy hook configuration of real_url

### ISSUE THREAD

**Issue by fcool** [b13/t3ext-seo_basics#6]
The ext_localconf parses the realurl-configuration and extend any key its find with a sitemap configuration. But realurl saves there not only domain based keys. The hooks are saved at that level too. The ext_localconf of seo_basics overwrites these hook-configuration with an array, which leads to a warning in TYPO3 4.* and to an exception in 6.2 (did not test 6.0 and 6.1)

**Comment by bmack** [comment]
Fixed this with 0.9.2
